#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
git ls-files | ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-javascript,sql -L -
mv .git/tags.$$ .git/tags
